// Code generated by "stringer -type Type -trimprefix Type"; DO NOT EDIT.

package kv1

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeInvalid-255]
	_ = x[TypeObject-0]
	_ = x[TypeString-1]
	_ = x[TypeInt32-2]
	_ = x[TypeFloat32-3]
	_ = x[TypePointer-4]
	_ = x[TypeWString-5]
	_ = x[TypeColor-6]
	_ = x[TypeUint64-7]
	_ = x[TypeEnd-8]
	_ = x[TypeInt64-10]
}

const (
	_Type_name_0 = "ObjectStringInt32Float32PointerWStringColorUint64End"
	_Type_name_1 = "Int64"
	_Type_name_2 = "Invalid"
)

var (
	_Type_index_0 = [...]uint8{0, 6, 12, 17, 24, 31, 38, 43, 49, 52}
)

func (i Type) String() string {
	switch {
	case i <= 8:
		return _Type_name_0[_Type_index_0[i]:_Type_index_0[i+1]]
	case i == 10:
		return _Type_name_1
	case i == 255:
		return _Type_name_2
	default:
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
